In [2]:
#lesson 1: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8188, 0.2130],
        [0.1804, 0.2203]]) 



In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9276, 0.5270, 0.3945],
        [0.8180, 0.9463, 0.2494]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [26]:
tensor = torch.ones(3, 3)
tensor[:,1:] = 0
tensor[:,2] = 2
print(tensor)

tensor([[1., 0., 2.],
        [1., 0., 2.],
        [1., 0., 2.]])


In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim=-1)
print(t1)

tensor([[1., 0., 2., 1., 0., 2., 1., 0., 2.],
        [1., 0., 2., 1., 0., 2., 1., 0., 2.],
        [1., 0., 2., 1., 0., 2., 1., 0., 2.]])


In [31]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")
print(f"tensor * tensor \n {tensor * 2}")

tensor.mul(tensor) 
 tensor([[1., 0., 4.],
        [1., 0., 4.],
        [1., 0., 4.]]) 

tensor * tensor 
 tensor([[1., 0., 4.],
        [1., 0., 4.],
        [1., 0., 4.]])
tensor * tensor 
 tensor([[2., 0., 4.],
        [2., 0., 4.],
        [2., 0., 4.]])


In [32]:
#Dot product

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]) 

tensor @ tensor.T 
 tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


In [33]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 2.],
        [1., 0., 2.],
        [1., 0., 2.]]) 

tensor([[6., 5., 7.],
        [6., 5., 7.],
        [6., 5., 7.]])


In [34]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [35]:
#A change in the tensor reflects in the NumPy array AND VICE VERSA

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [36]:
n = np.ones(5)
t = torch.from_numpy(n)

In [37]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
